/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projectdsaa;

/**
 *
 * @author finnb
 */
public class FornGUI extends javax.swing.JFrame {

    /**
     * Creates new form FornGUI
     */
    public FornGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        FormPage = new javax.swing.JPanel();
        PriceLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        OutPutField = new javax.swing.JTextArea();
        PriceFLD = new javax.swing.JTextField();
        SpotIDLbl = new javax.swing.JLabel();
        FindSpotbtn = new javax.swing.JButton();
        SpotIdFLD = new javax.swing.JTextField();
        AddSpotBTN = new javax.swing.JButton();
        Removebtn = new javax.swing.JButton();
        Locationlbl = new javax.swing.JLabel();
        LocationFLd = new javax.swing.JTextField();
        UpdateSpotbtn = new javax.swing.JButton();
        ParkingHistory = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        DisplayHistoryField = new javax.swing.JTextArea();
        ViewHistoryBTN = new javax.swing.JButton();
        ParkingList = new javax.swing.JPanel();
        FindSpotBTN = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        WaitingQueue = new javax.swing.JPanel();
        ViewQueuebtn = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PriceLbl.setText("Price:");

        OutPutField.setColumns(20);
        OutPutField.setRows(5);
        jScrollPane1.setViewportView(OutPutField);

        SpotIDLbl.setText("Spot Id:");

        FindSpotbtn.setText("View Space");

        SpotIdFLD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SpotIdFLDActionPerformed(evt);
            }
        });

        AddSpotBTN.setText("Add spot");
        AddSpotBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddSpotBTNActionPerformed(evt);
            }
        });

        Removebtn.setText("Remove Spot");
        Removebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemovebtnActionPerformed(evt);
            }
        });

        Locationlbl.setText("Location:");

        LocationFLd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocationFLdActionPerformed(evt);
            }
        });

        UpdateSpotbtn.setText("Update Spot");

        javax.swing.GroupLayout FormPageLayout = new javax.swing.GroupLayout(FormPage);
        FormPage.setLayout(FormPageLayout);
        FormPageLayout.setHorizontalGroup(
            FormPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormPageLayout.createSequentialGroup()
                .addGroup(FormPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FormPageLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FormPageLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(FindSpotbtn)
                        .addGap(45, 45, 45)
                        .addComponent(AddSpotBTN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Removebtn)
                        .addGap(18, 18, 18)
                        .addComponent(UpdateSpotbtn))
                    .addGroup(FormPageLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(FormPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(FormPageLayout.createSequentialGroup()
                                .addComponent(PriceLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PriceFLD, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(FormPageLayout.createSequentialGroup()
                                .addComponent(SpotIDLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SpotIdFLD, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(FormPageLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Locationlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LocationFLd, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        FormPageLayout.setVerticalGroup(
            FormPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormPageLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(FormPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PriceLbl)
                    .addComponent(PriceFLD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FormPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpotIDLbl)
                    .addComponent(SpotIdFLD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Locationlbl)
                    .addComponent(LocationFLd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(FormPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FindSpotbtn)
                    .addComponent(AddSpotBTN)
                    .addComponent(Removebtn)
                    .addComponent(UpdateSpotbtn))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Form Page", FormPage);

        DisplayHistoryField.setColumns(20);
        DisplayHistoryField.setRows(5);
        jScrollPane2.setViewportView(DisplayHistoryField);

        ViewHistoryBTN.setText("View History");

        javax.swing.GroupLayout ParkingHistoryLayout = new javax.swing.GroupLayout(ParkingHistory);
        ParkingHistory.setLayout(ParkingHistoryLayout);
        ParkingHistoryLayout.setHorizontalGroup(
            ParkingHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ParkingHistoryLayout.createSequentialGroup()
                .addGroup(ParkingHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ParkingHistoryLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(ViewHistoryBTN))
                    .addGroup(ParkingHistoryLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(265, Short.MAX_VALUE))
        );
        ParkingHistoryLayout.setVerticalGroup(
            ParkingHistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ParkingHistoryLayout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addComponent(ViewHistoryBTN)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
        );

        jTabbedPane2.addTab("Parking History", ParkingHistory);

        FindSpotBTN.setText("Find Spot ");
        FindSpotBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindSpotBTNActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        javax.swing.GroupLayout ParkingListLayout = new javax.swing.GroupLayout(ParkingList);
        ParkingList.setLayout(ParkingListLayout);
        ParkingListLayout.setHorizontalGroup(
            ParkingListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ParkingListLayout.createSequentialGroup()
                .addGroup(ParkingListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ParkingListLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ParkingListLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(FindSpotBTN)))
                .addContainerGap(309, Short.MAX_VALUE))
        );
        ParkingListLayout.setVerticalGroup(
            ParkingListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ParkingListLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(FindSpotBTN)
                .addGap(36, 36, 36)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Parking List ", ParkingList);

        ViewQueuebtn.setText("View Queue");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane4.setViewportView(jTextArea2);

        javax.swing.GroupLayout WaitingQueueLayout = new javax.swing.GroupLayout(WaitingQueue);
        WaitingQueue.setLayout(WaitingQueueLayout);
        WaitingQueueLayout.setHorizontalGroup(
            WaitingQueueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WaitingQueueLayout.createSequentialGroup()
                .addGroup(WaitingQueueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WaitingQueueLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(ViewQueuebtn))
                    .addGroup(WaitingQueueLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(309, Short.MAX_VALUE))
        );
        WaitingQueueLayout.setVerticalGroup(
            WaitingQueueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WaitingQueueLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(ViewQueuebtn)
                .addGap(68, 68, 68)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Waiting Queue", WaitingQueue);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SpotIdFLDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SpotIdFLDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SpotIdFLDActionPerformed

    private void AddSpotBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddSpotBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddSpotBTNActionPerformed

    private void RemovebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemovebtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RemovebtnActionPerformed

    private void LocationFLdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocationFLdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LocationFLdActionPerformed

    private void FindSpotBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindSpotBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FindSpotBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FornGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FornGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FornGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FornGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FornGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddSpotBTN;
    private javax.swing.JTextArea DisplayHistoryField;
    private javax.swing.JButton FindSpotBTN;
    private javax.swing.JButton FindSpotbtn;
    private javax.swing.JPanel FormPage;
    private javax.swing.JTextField LocationFLd;
    private javax.swing.JLabel Locationlbl;
    private javax.swing.JTextArea OutPutField;
    private javax.swing.JPanel ParkingHistory;
    private javax.swing.JPanel ParkingList;
    private javax.swing.JTextField PriceFLD;
    private javax.swing.JLabel PriceLbl;
    private javax.swing.JButton Removebtn;
    private javax.swing.JLabel SpotIDLbl;
    private javax.swing.JTextField SpotIdFLD;
    private javax.swing.JButton UpdateSpotbtn;
    private javax.swing.JButton ViewHistoryBTN;
    private javax.swing.JButton ViewQueuebtn;
    private javax.swing.JPanel WaitingQueue;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
